### ISSUE TITLE
tried running the python LSM9DS0-gyro-accel-compass

### ISSUE THREAD

**Issue by xmen4u** [mwilliams03/BerryIMU#2]
sudo python berryIMU.py
Result: 
"Traceback (most recent call last):
  File "berryIMU.py", line 126, in <module>
    writeACC(CTRL_REG1_XM, 0b01100111) #z,y,x axis enabled, continuos update,  100Hz data rate
  File "berryIMU.py", line 38, in writeACC
    bus.write_byte_data(ACC_ADDRESS , register, value)
IOError: [Errno 5] Input/output error"

my run of "sudo /usr/sbin/i2cdetect -y 1" resulted:
 0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- --
10: -- -- -- -- -- -- -- -- -- -- -- UU -- -- -- --
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- UU -- -- -- --
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
70: -- -- -- -- -- -- -- --

and of "sudo /usr/sbin/i2cdetect -y 0" resulted in:
Error: Could not open file `/dev/i2c-0' or `/dev/i2c/0': No such file or directory

Have i done something wrong? thank you!

**Comment by xmen4u** [comment]
I've connected it to the other output (The 3 pin 2 row female header) and it worked. What does it mean? thank you

**Comment by xmen4u** [comment]
reconnected, works! probably loss cable issue!
